CREATE TABLE IF NOT EXISTS "m_outlet" (
	"id" serial PRIMARY KEY NOT NULL,
	"outlet_code" varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	"brand" varchar(100) NOT NULL,
	"unique_name" varchar(100) NOT NULL,
	"address_line" varchar(300) NOT NULL,
	"sub_district" varchar(100) NOT NULL,
	"district" varchar(100) NOT NULL,
	"city_or_regency" varchar(100) DEFAULT '',
	"postal_code" integer NOT NULL,
	"latitude" varchar(225) DEFAULT '',
	"longitude" varchar(225) DEFAULT '',
	"outlet_type" varchar(50) DEFAULT '',
	"region" varchar(50) DEFAULT '',
	"area" varchar(50) DEFAULT '',
	"cycle" varchar(50) DEFAULT '',
	"is_active" integer DEFAULT 1 NOT NULL,
	"visit_day" varchar(50) NOT NULL,
	"odd_even" varchar(20) NOT NULL,
	"photos" json DEFAULT '[]',
	"remarks" text DEFAULT '',
	"created_by" varchar(20),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_by" varchar(20),
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"deleted_by" varchar(20),
	"deleted_at" timestamp
);
