ALTER TABLE "activity_md" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "activity_md" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "activity_md" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "activity_md_detail" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "activity_md_detail" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "activity_md_detail" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan_schedule" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan_schedule" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "call_plan_schedule" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_brand" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_brand" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_brand" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_sio_type" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_sio_type" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_sio_type" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch_target" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch_target" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_batch_target" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_outlet" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_outlet" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_outlet" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user" ALTER COLUMN "email" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user" ALTER COLUMN "deleted_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user_role" ALTER COLUMN "created_by" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "m_user_role" ALTER COLUMN "updated_by" SET DATA TYPE varchar(100);